apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout-voting-app.yaml
- rollout-result-app.yaml
- voting-app-service.yaml
- result-app-service.yaml
- ingress.yaml
- voting-app-preview-service.yaml
- result-app-preview-service.yaml
images:
- name: devendradhoot/vote
  newTag: v1
- name: devendradhoot/result
  newTag: v1
