apiVersion: v1
kind: Service
metadata:
  name: result-service-preview
  labels:
    name: result-service
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30031
  selector:
    name: result-service
   type: NodePort  
    
